### ISSUE TITLE
Scaled dot product attention backward does not work with MacOS

### ISSUE THREAD

**Issue by brappier** [liuliu/s4nnc#21]
snippet:
```
  let keys = tokeys(c).reshaped(.NHWC(b, t, h, k)).identity()
  var queries = (  toqueries(x)).reshaped(.NHWC(b, hw, h, k)).identity().identity()
  var values = tovalues(c).reshaped(.NHWC(b, t, h, k))
  
  let scaledDotProductAttention = ScaledDotProductAttention(
    scale: 1.0 / Float(k).squareRoot(), multiHeadOutputProjectionFused: true)
  var out = scaledDotProductAttention(queries, keys, values).reshaped([b, hw, h * k])
```

error when MFA is enabled :
```
loc("mps_matmul_1"("(mpsFileLoc): ../Files/MPSGraphUtilities.mm":39:0)): error: incompatible dimensions
loc("mps_matmul_1"("(mpsFileLoc): ..Files/MPSGraphUtilities.mm":39:0)): error: invalid shape
```

error when mfa is disabled 

```
Assertion failed: (isStaticMPSType(type)), function setStaticJITypeForValue, file MPSRuntime_Project.h, line 501.
```

fwd works fine but in backward i get error

**Comment by liuliu** [comment]
hmmm. We use this in Draw Things (and we use public version of s4nnc, obviously)'s LoRA training code.

One thing I would call out though, because doing LoRA requires us to have the Dense layer separately, so we only enable `multiHeadOutputProjectionFused: true` in inference side, for training side, this is false. That is probably why you get this error.

Let me know if that is the case so I can close this.

**Comment by brappier** [comment]
That works, thanks
