### ISSUE TITLE
How to load weights to a model from a dictionary in memory

### ISSUE THREAD

**Issue by brappier** [liuliu/s4nnc#4]
I have a dictionary mapping from key -> Data . How can I load weights to the model from the dictionary? 
We can assume that we have keys of the same name as sqllite datastore. and we also have the dims of each weight. 

is there any snippet where, i can set the i'th layer / paramater of a Model given some data in memory?

**Comment by liuliu** [comment]
See example from swift-diffusion: https://github.com/liuliu/swift-diffusion/blob/main/examples/unet/main.swift#L231 if you retain the individual model, you can set their parameters by copying a tensor into it.

There are also some other newer alternative way to do this: https://liuliu.github.io/s4nnc/documentation/nnc/dynamicgraph/store/read(_:model:reader:) This method now can take a closure, inside you can return different tensors based on the name (although these name usually useless unless you get the mapping from `parameters(for: .weight).name` before).

**Comment by brappier** [comment]
@liuliu  thanks a lot. I like the 2nd way. 
What is ModelReaderResult? so i just return 1 if its successful and return 0 if its not? 
Shouldnt the closure be String -> Tensor,   why does it take 2 strings as input?

**Comment by brappier** [comment]
Is there any example to use the read function in this way in current form?
Also, is there any simple function i can use to set ith weight of the model?

**Comment by liuliu** [comment]
Unfortunately, no code available in public. I can share the code in private repo where I use that to support clip skip:
```

      graph.openStore(filePath) {
        if clipSkip > 1 {
          $0.read("text_model", model: textModel) { name, _, _ in
            // Retrieve the right final layer norm parameters.
            if name == "__text_model__[t-\(98 - (min(clipSkip, 12) - 1) * 8)-0]" {
              return .continue("__text_model__[t-98-0]")
            } else if name == "__text_model__[t-\(98 - (min(clipSkip, 12) - 1) * 8)-1]" {
              return .continue("__text_model__[t-98-1]")
            }
            return .continue(name)
          }
        } else {
          $0.read("text_model", model: textModel)
        }
      }
```

As for simple function to set ith weight, there ain't any at the moment. The best is to follow the example to write an accompanied reader closure and as you build up the model, return these all the way up to the top to keep the logic sane. This is how I implemented safetensors / pickle file loading logic.

**Comment by brappier** [comment]
what does .continue(new_name) mean? does it contain the variable name of the next variable to read?

what do you mean by renaming?

**Comment by liuliu** [comment]
Because the model might changed (for example, in this one, the model are missing a few layers), so the default weight name in SQLite might be different if it is just blindly query. rename allows you to retrieve the original weight when the model is in different shape.

Similar to when you changed a variable in `nn.Module` (of PyTorch) and you need to rename if you want to load old checkpoint file.

`.continue(newName)` gives the right name to the reader so it can lookup and load the weight by that name.

**Comment by brappier** [comment]
Okay thank, so the variable name is coming from the sqlite file? and you when you do .continue(newName) it basically reads name from the database and writes at the layer newName  ?

**Comment by brappier** [comment]
also there are no docs about rawValue for Store. what does that do?

**Comment by brappier** [comment]
You gave me the example for read, where i can pass my closure. But that is a method for store, which needs sqlite database. How can i create a Store withot any database.

**Comment by liuliu** [comment]
Yeah, the current API requires to be used within a `graph.openStore()` call. Used without that call probably need to change the API and expose that.

**Comment by brappier** [comment]
```
graph!.openStore("/home/samanthagoldberg/dummy.txt") {
            $0.read("unet", model: unet! ) { name, a2, ten in
              ten = cached_weights[name]!
              return .continue(name)
            }
          }
```
this runs but it seems to not set the weights. say i have cached the Tensors in `cached_weights` . now i am setting the weight tensors of the graph. but it does not seem to set it.

**Comment by liuliu** [comment]
Yeah, as I said earlier, the API is a bit rough, it probably need to work like this:
```
graph!.openStore("/home/samanthagoldberg/dummy.txt") {
            $0.read("unet", model: unet! ) { name, a2, ten in
              graph.variable(Tensor<Float>(ten))[0..<x, 0..<y, 0..<z] = cachedWeights[name]
              return .final
            }
          }
```
As I said earlier, the API is subject to change because of these issues.

**Comment by brappier** [comment]
this i am guessing is copying the weights from cachedWeghts?
I am caching the GPU Tensors themselves. Can it be used by model without copying? so that memory used is not double?

**Comment by brappier** [comment]
cant i just point the data source of ten to my cached location?
This is how i am generating the cache
```
 graph!.openStore(".sd-v1.4.ckpt") {
  $0.read("unet", model: unet!)
}

graph!.openStore("/dev/null") {
  print("kallu", $0)
  $0.read("unet", model: unet! ) { name, a2, ten in
    cached_weights[name] = ten
    return .continue(name)
  }
}
```

**Comment by liuliu** [comment]
I don't have a good way to accomplish what you have in mind other than accessing individual model's weight / bias and copy out / copy in with the copy method. This way is tried and worked.

This API (read with reader closure) probably is not what you are looking for. It will change, and it is designed to help me do some manipulations during weight loading process, such as combining LoRA weights, or directing to a different name. It is not meant to be a method to iterate through parameters and assigning them in or out.

**Comment by brappier** [comment]
okay, 
so while creating the model, can i set the weights from tensor which are already in GPU memory without copying? 
I see you are calling eg. ` fc0.parameters(for: .weight).copy(from: tensor))` in your examples/unet. 
Any work around for not using 2x memory?

**Comment by liuliu** [comment]
Unfortunately that is not possible due to the design. model1 and model2 manages their own parameter allocations separately. There is no way to allow model2 to inherit allocated parameters from model1.

The only way to reuse parameter (in current API surface) is to go through ModelBuilder, which will rebuild the graph but keep the allocated parameters.

**Comment by brappier** [comment]
Okay thanks for the clarification! 

Are you sure we have to do return .final in the closure, and not return .continue(name) . looks like if i do return .final, its messing up the weights. 


Also, any other cleaner way to copy data to a tensor, (i store it an any form you want) ? rather than casting it to a variable and then setting the data.

**Comment by liuliu** [comment]
> Are you sure we have to do return .final in the closure, and not return .continue(name) . looks like if i do return .final, its messing up the weights.

When you return `.continue` it will continue to read that weight with the given name. I think that is probably why the weight is not messed up.

> Also, any other cleaner way to copy data to a tensor, (i store it an any form you want) ? rather than casting it to a variable and then setting the data.

The best supported way is to use these methods: https://liuliu.github.io/s4nnc/documentation/nnc/model/parameters-swift.class/copied(_:)/ https://liuliu.github.io/s4nnc/documentation/nnc/model/parameters-swift.class/copy(from:)-51ulz to get weights out and in to a model. The other way (e.g. as the reader closure) is subject to dramatic changes to the API and only probably will get stablized after LoRA supported and in-the-wild for a while.

**Comment by brappier** [comment]
copy(from:) seems a much better way!! Thanks, Liu!
One last question, 
give a model, how do i iterate over all the params?

**Comment by liuliu** [comment]
> copy(from:) seems a much better way!! Thanks, Liu! One last question, give a model, how do i iterate over all the params? So that i can set copy tensors to each param one by one. is not possible, unless we save the layers in the class.

Yeah, right now, there is no provided way to do that. You need to follow the examples/unet/main.swift to save each layer and iterate that way (if you follow the style of returning a reader closure along with the model, it is not that foreign).

> in the examples you seem to make fucntions instead of classes withall paramaters attached to object( pytorch style), are you doing that because it saves memory somehow?

I don't think so. If it saves memory, it is the side-effect. The model construction from s4nnc is always functional (i.e. return a generic Model object from a function, rather than PyTorch's creating new class off `nn.Module`). The way to load parameter I think is pretty clean too, as each construction follows basically this style: `func ResBlock(parameter) -> (Model, ReaderClosure)` . It might help depending on how you write your Reader function. In `examples/pickle/main.swift`, the reader function accesses Pickle archive one at a time, so the parameter copy is one at a time, thus, never incur double-RAM when reading because even the Model is fully allocated with its parameters, the parameter loading happens piece-by-piece inside the reader function.

**Comment by brappier** [comment]
` graph.variable(Tensor<Float>(ten))[0..<x, 0..<y, 0..<z] = cachedWeights[name]` gives seg fualt

if i just set the first element of the weights, it still gives seg fualt,

```
if(name == "__unet__[t-149-0]"){
                graph!.variable(Tensor<Float16>(ten))[0,0,0,0] = 0
              }
```

is there any clean way to set the data of the tensor, from the closure?

**Comment by liuliu** [comment]
hmmm, yeah. I probably need to refactor the API interface. I didn't tried that although it should work in C side, but it is no surprise really that on Swift side it might have issues.

This API will be much better when I get LoRA end-to-end worked, because that's where I plan to use this (at model read time, merging LoRA weights directly into the main model).
